a = int(input())
m = set()
m.update(list(map(int,input().split())))
b = int(input())
n = set()
n.update(list(map(int,input().split())))
total = set()
total.update(m.difference(n))
total.update(n.difference(m))
total = list(total)
total = sorted(total)
print ("\n".join(map(str,total)))
